function timestamp() {
  // sometime in the last 30 days
  const stampy =
    Date.now() - Math.floor(Math.random() * 1000 * 60 * 60 * 24 * 30);
  return new Date(stampy).toISOString();
}

export const photos = [
  {
    name: 'Andi O',
    description: 'Book time',
    altText: 'This is Andi O with a book',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'wy3bju',
      filename: 'andi_wy3bju.jpg',
      originalFilename: 'andi.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/andi_wy3bju',
        version: 1576791335,
        width: 3093,
        height: 4639,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 264850,
        type: 'upload',
        etag: 'e1fdf84d5126b6ca2e1c8ef9532be5a5',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/andi_wy3bju.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/andi_wy3bju.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Barron V',
    description: 'Collars for Days',
    altText: 'This is Barron V in a jacket',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'woxtot',
      filename: 'bar_woxtot.jpg',
      originalFilename: 'bar.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/bar_woxtot',
        width: 3430,
        height: 5144,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 225400,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/bar_woxtot.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/bar_woxtot.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Blinky Bass',
    description: 'Bass chin!',
    altText: 'This is a bass player rocking it',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'ttrd9s',
      filename: 'bass-live_ttrd9s.jpg',
      originalFilename: 'bass-live.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/bass-live_ttrd9s',
        width: 7020,
        height: 4680,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 149160,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/bass-live_ttrd9s.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/bass-live_ttrd9s.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Beth S',
    description: 'Side Beth!',
    altText: 'This is Beth S looking at a camera',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'zaiiic',
      filename: 'beth_zaiiic.jpg',
      originalFilename: 'beth.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/beth_zaiiic',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 221450,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/beth_zaiiic.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/beth_zaiiic.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'All Time Low',
    description: 'Cute face!!',
    altText: 'Singer of All Time Low with an audience behind them',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'eo6yax',
      filename: 'alltimelow-live_eo6yax.jpg',
      originalFilename: 'alltimelow-live.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/alltimelow-live_eo6yax',
        width: 5616,
        height: 3744,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 213420,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/alltimelow-live_eo6yax.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/alltimelow-live_eo6yax.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Astro Boy',
    description: 'Wow, these eyes',
    altText: 'No chairs in sight',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'i9kt1q',
      filename: 'astro_i9kt1q.jpg',
      originalFilename: 'astro.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/astro_i9kt1q',
        width: 5616,
        height: 3744,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 192480,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/astro_i9kt1q.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/astro_i9kt1q.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Kumil?',
    description: 'OMG THOSE EYES',
    altText: 'Okay and a drink',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'nbyjch',
      filename: 'kum_nbyjch.jpg',
      originalFilename: 'kum.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/kum_nbyjch',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 270890,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/kum_nbyjch.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/kum_nbyjch.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Kurt S',
    description: 'Brow Town',
    altText: 'The arms say no',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'm1hbxb',
      filename: 'kurt_m1hbxb.jpg',
      originalFilename: 'kurt.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/kurt_m1hbxb',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 261370,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/kurt_m1hbxb.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/kurt_m1hbxb.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Hands Like Houses',
    description: 'Hands Promo for Late Night',
    altText: 'A gaggle of handsomes',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'zgtx0p',
      filename: 'hands_zgtx0p.jpg',
      originalFilename: 'hands.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/hands_zgtx0p',
        width: 7020,
        height: 4680,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 187100,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/hands_zgtx0p.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893084/mt/hands_zgtx0p.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Hasan M',
    description: 'The man with the beautiful eyes',
    altText: 'Young man, looking good',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'vczmd2',
      filename: 'hasan_vczmd2.jpg',
      originalFilename: 'hasan.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/hasan_vczmd2',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 308780,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/hasan_vczmd2.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/hasan_vczmd2.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Lindsey Ames',
    description: 'The distance',
    altText: 'What is off camera',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'lkjn7g',
      filename: 'lind_lkjn7g.jpg',
      originalFilename: 'lind.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/lind_lkjn7g',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 205960,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/lind_lkjn7g.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/lind_lkjn7g.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Paramore',
    description: 'Leading the way',
    altText: 'Lets gooooo',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'nw8nak',
      filename: 'paramore-live_nw8nak.jpg',
      originalFilename: 'paramore-live.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/paramore-live_nw8nak',
        width: 5616,
        height: 3744,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 125800,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/paramore-live_nw8nak.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/paramore-live_nw8nak.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Oliver',
    description: 'In the thick of it',
    altText: 'Heavy heavy',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'l6xocb',
      filename: 'oliver-live_l6xocb.jpg',
      originalFilename: 'oliver-live.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/oliver-live_l6xocb',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 146960,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/oliver-live_l6xocb.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/oliver-live_l6xocb.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Tay',
    description: 'Chillin',
    altText: 'Sitting on the bed',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'dewat2',
      filename: 'tay_dewat2.jpg',
      originalFilename: 'tay.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/tay_dewat2',
        width: 3744,
        height: 5616,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 150440,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/tay_dewat2.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/tay_dewat2.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'The Used Duex',
    description: 'Good good',
    altText: 'Live from the stage',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'dgvwln',
      filename: 'used-live_dgvwln.jpg',
      originalFilename: 'used-live.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/used-live_dgvwln',
        width: 6720,
        height: 4480,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 640450,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/used-live_dgvwln.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/used-live_dgvwln.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'Yellowcard',
    description: 'Thinking about being nice',
    altText: 'Hi friends, we are Yellowcard',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'rdjm6p',
      filename: 'yellowcard_rdjm6p.jpg',
      originalFilename: 'yellowcard.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/yellowcard_rdjm6p',
        width: 7020,
        height: 4680,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 287540,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/yellowcard_rdjm6p.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/yellowcard_rdjm6p.jpg',
        original_filename: 'file',
      },
    },
  },
  {
    name: 'The Used',
    description: 'Guitar Rock',
    altText: 'Friend of the band, guitar',
    status: 'PUBLISHED',
    backgroundImage: false,
    image: {
      id: 'p3xpfc',
      filename: 'used-live2_p3xpfc.jpg',
      originalFilename: 'used-live2.jpg',
      mimetype: 'image/jpeg',
      encoding: '7bit',
      _meta: {
        public_id: 'mt/used-live2_p3xpfc',
        width: 4480,
        height: 6720,
        format: 'jpg',
        resource_type: 'image',
        created_at: timestamp(),
        tags: [],
        bytes: 683840,
        type: 'upload',
        placeholder: false,
        url:
          'http://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/used-live2_p3xpfc.jpg',
        secure_url:
          'https://res.cloudinary.com/dk3ahfitr/image/upload/v1616893085/mt/used-live2_p3xpfc.jpg',
        original_filename: 'file',
      },
    },
  },
];

export const galleries = [
  {
    name: 'Music',
    description: 'A nice story about my music gallery',
    status: 'PUBLISHED',
  },
  {
    name: 'Comedy',
    description: 'A GREAT story about this comedy photo album',
    status: 'PUBLISHED',
  },
];
